version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_cqrs
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:latest
    container_name: postgres_cqrs
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: read_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  redis:
#    image: redis:latest
#    container_name: redis_cqrs
#    restart: always
#    ports:
#      - "6379:6379"

volumes:
  mongo_data:
  postgres_data:
